---
title: "my-website"
author: "Kyle Shedd"
date: "November 29, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, echo = FALSE}
suppressPackageStartupMessages({
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
})
```

## Load escapement data from file
This file came from [KNB](https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1).
```{r, cache = TRUE}
escapement <- read.csv("data/knb.92020.1.csv", 
                       stringsAsFactors = FALSE)
```

## Determine median annual escapement by species
Create pipeline and plot object.
```{r}
median_esc <- escapement %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, Year, Location) %>% 
  summarise(escapement = sum(DailyCount)) %>% 
  group_by(Species) %>% 
  summarise(median_escapement = median(escapement))

ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```

## Interactive table
```{r}
datatable(median_esc)
```

## Create a map with leaflet
First filter for distinct locations and drop `NA` values.
```{r}
locations <- escapement %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

datatable(locations)
```

Add map.
```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ -abs(Longitude), ~ Latitude, popup = ~ Location)
```
